// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    return $('.post img').each(function() {
      return $(this).on('click', function() {
        return window.open($(this).attr('src'));
      });
    });
  });

}).call(this);
