// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    return $('a').each(function() {
      var href;
      href = $(this).attr("href");
      if (href.indexOf(window.location.origin) === -1 && href[0] !== "/") {
        return $(this).attr('target', '_blank');
      }
    });
  });

}).call(this);
